version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.16.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.16.1

      - image: trufflesuite/ganache-cli:v6.12.1
        command: ganache-cli --mnemonic "test" -e 1000 -i 123456789 --chainId 123456789

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run: npm test

  lint-tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.16.1

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run: npm run eslint
      - run: npm run prettier-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint-tests:
          requires:
            - build
