version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:22.16.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run compile
      - run: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  test:
    docker:
      # specify the version you desire here
      - image: cimg/node:22.16.0

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run: npm test

  lint-tests:
    docker:
      # specify the version you desire here
      - image: cimg/node:22.16.0

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ./
      - run: npm run eslint
      - run: npm run prettier-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint-tests:
          requires:
            - build
